# FICHIER: .github/workflows/ci.yml (NOUVEAU)
# Pipeline d'Intégration Continue. Automatise la validation à chaque push.
# C'est la "Fitness Function" qui garantit la santé du projet en continu.
name: CI - Analyzer Engine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Run linter (Ruff)
        run: ruff check .
      - name: Run formatter check (Black)
        run: black --check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Installer les dépendances de test
        pip install pytest pytest-asyncio pytest-mock pytest-cov testcontainers[postgres] aiosqlite
    
    - name: Run tests and generate coverage report
      env:
        # L'URL de la BDD est construite à partir des services de la CI
        DATABASE_URL: postgresql://test:test@localhost:5432/test
        LLM_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      run: |
        pytest --cov=ingestion --cov=core --cov-report=term-missing --cov-fail-under=85